from django.urls import path
from .views import (
    MissingInvoiceAPIView, 
    InvoiceListingAPIView, 
    NewInvoiceAPIView ,
    InvoiceIncomeAPIView, 
    InvoiceCountAPIView,
    InvoicePromotorPieAPIView,
    FirstUnpaidDateAPIView,
    InvoiceSingleAPIView,
    InvoiceLogListingAPIView, 
    InvoiceReminderListingAPIView, 
    InvoicePaymentHistoryListingAPIView,
    InvoiceUpload,
    NewInvoiceLog,
    NewInvoiceReminder,
    NewInvoicePaymentHistory,
    UpdateInvoiceAPIView,
    InvoiceDebtAPIView,
    FirstUnpaidInvoiceAPIView,
    InvoiceEdHistoryListingAPIView
    )
 
urlpatterns = [
    path('create', NewInvoiceAPIView.as_view()),
    path('missing', MissingInvoiceAPIView.as_view()),
    path('list', InvoiceListingAPIView.as_view({'get': 'list'})),
    path('earned', InvoiceIncomeAPIView.as_view()),
    path('debt',InvoiceDebtAPIView.as_view()),
    path('invoiced', InvoiceCountAPIView.as_view()),
    path('promotor_pie', InvoicePromotorPieAPIView.as_view({'get': 'get'})),
    path('firstunpaiddate', FirstUnpaidDateAPIView.as_view()),
    path('firstunpaidinvoice', FirstUnpaidInvoiceAPIView.as_view()),
    path('log/<int:id>',InvoiceLogListingAPIView.as_view()),
    path('log',NewInvoiceLog.as_view()),
    path('reminder/<int:id>',InvoiceReminderListingAPIView.as_view()),
    path('reminder',NewInvoiceReminder.as_view()),
    path('history/<int:id>',InvoicePaymentHistoryListingAPIView.as_view()),
    path('history',NewInvoicePaymentHistory.as_view()),
    path('epd/<int:id>',InvoiceEdHistoryListingAPIView.as_view()),
    path('<int:id>',InvoiceSingleAPIView.as_view()),
    path('upload',InvoiceUpload.as_view()),
    path('update/<int:id>', UpdateInvoiceAPIView.as_view()),
]
