# Generated by Django 2.1.2 on 2018-11-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_firstname', models.CharField(max_length=30, unique=True)),
                ('contact_lastname', models.CharField(max_length=50)),
                ('contact_type', models.CharField(max_length=30)),
                ('contact_fullname', models.CharField(max_length=30, null=True)),
                ('contact_byname', models.CharField(max_length=30)),
                ('contact_cdate', models.DateField(auto_now_add=True)),
                ('contact_mdate', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='ContactStaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawname', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('db', models.CharField(max_length=20, null=True)),
                ('user', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'contact_staging',
            },
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cu_contact_id', models.ForeignKey(db_column='cu_contact_id', on_delete='', to='contacts.Contact')),
            ],
            options={
                'db_table': 'contact_user',
            },
        ),
    ]
