# Generated by Django 2.1.2 on 2018-11-29 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuser',
            name='cu_id',
            field=models.ForeignKey(db_column='cu_id', on_delete='', to=settings.AUTH_USER_MODEL),
        ),
    ]
