# Generated by Django 2.1.2 on 2018-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactuser_cu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_byname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_fullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
