# Generated by Django 2.1.2 on 2018-11-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20181129_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_taxid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
