# Generated by Django 2.1.2 on 2019-01-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20181129_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['contact_firstname', 'contact_lastname', 'contact_fullname', 'contact_taxid', 'contact_email']},
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
