# Generated by Django 2.1.2 on 2019-05-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20190116_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
