# Generated by Django 2.1.2 on 2019-06-30 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_contact_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['contact_firstname', 'contact_lastname', 'contact_fullname', 'contact_taxid', 'contact_email', 'contact_type']},
        ),
    ]
