# Generated by Django 2.1.2 on 2018-11-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('fac_key', models.AutoField(primary_key=True, serialize=False)),
                ('fac_serie', models.CharField(max_length=10)),
                ('fac_folio', models.IntegerField()),
                ('fac_emisorrfc', models.CharField(max_length=30)),
                ('fac_emisornombre', models.TextField()),
                ('fac_receptorrfc', models.CharField(max_length=30)),
                ('fac_receptornombre', models.TextField()),
                ('fac_total', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('fac_observaciones', models.TextField(blank=True, null=True)),
                ('fac_xml', models.TextField()),
                ('fac_fechapago', models.DateField()),
                ('fac_fecha', models.DateTimeField()),
                ('fac_cdate', models.DateTimeField()),
                ('fac_subtotal', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('fac_iva', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('fac_payments', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('fac_isactive', models.BooleanField(default=True)),
                ('fac_contact', models.TextField(blank=True, null=True)),
                ('fac_lastreminder', models.IntegerField(default=0)),
                ('fac_pagada', models.IntegerField(default=0)),
                ('fac_complemento', models.TextField(null=True)),
                ('fac_idclient', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'cbr_facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLog',
            fields=[
                ('log_key', models.AutoField(primary_key=True, serialize=False)),
                ('log_text', models.TextField()),
                ('log_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'cbr_bitacoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoicePaymentHistory',
            fields=[
                ('his_key', models.AutoField(primary_key=True, serialize=False)),
                ('his_date', models.DateField()),
                ('his_amount', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
            ],
            options={
                'db_table': 'cbr_historialpagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceReminders',
            fields=[
                ('rem_key', models.AutoField(primary_key=True, serialize=False)),
                ('rem_text', models.TextField()),
                ('rem_datetime', models.DateTimeField()),
                ('rem_isactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cbr_reminders',
                'managed': False,
            },
        ),
    ]
