# Generated by Django 2.1.2 on 2019-06-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicelog',
            options={'managed': False, 'ordering': ['log_datetime', 'log_cuser', 'log_cuser__first_name', 'log_cuser__last_name']},
        ),
    ]
