# Generated by Django 2.1.2 on 2019-07-03 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0002_auto_20190604_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceEdHistory',
            fields=[
                ('ed_key', models.AutoField(primary_key=True, serialize=False)),
                ('ed_newdate', models.DateTimeField()),
                ('ed_olddate', models.DateTimeField()),
                ('ed_invoice', models.ForeignKey(db_column='his_invoice', on_delete='', to='invoices.Invoice')),
                ('ed_user', models.ForeignKey(blank=True, db_column='ed_user', null=True, on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbr_edhistory',
                'managed': True,
            },
        ),
    ]
