# Generated by Django 2.1.2 on 2019-07-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoiceedhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceedhistory',
            name='ed_newdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceedhistory',
            name='ed_olddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
