# Generated by Django 2.1.2 on 2019-07-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20190703_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFileLog',
            fields=[
                ('ifl_key', models.AutoField(primary_key=True, serialize=False)),
                ('ifl_filepath', models.TextField()),
                ('ifl_date', models.DateTimeField(auto_now_add=True)),
                ('ifl_pdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('ifl_status', models.CharField(default='PENDING', max_length=30)),
                ('ifl_invoice', models.ForeignKey(blank=True, db_column='ifl_invoice', null=True, on_delete='', to='invoices.Invoice')),
            ],
            options={
                'db_table': 'cbr_invoicefilelog',
                'managed': True,
            },
        ),
    ]
