# Generated by Django 2.1.2 on 2019-01-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190116_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolename',
            field=models.ForeignKey(db_column='rolename', on_delete='', to='users.Role', to_field='role_name'),
        ),
    ]
