# Generated by Django 2.1.2 on 2019-01-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190121_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_key',
            field=models.ForeignKey(db_column='role_key', default=1, on_delete='', to='users.Role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='rolename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
