# Generated by Django 2.1.2 on 2019-01-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190121_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', 'first_name', 'last_name', 'role_key']},
        ),
    ]
