# Generated by Django 2.1.2 on 2019-01-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190121_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', 'first_name', 'last_name', 'role_key', 'role_key__role_label']},
        ),
    ]
