# Generated by Django 2.1.2 on 2019-05-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', 'first_name', 'last_name', 'role_key', 'role_key__role_label', 'role_key__role_name']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='rolename',
        ),
    ]
